# Generated by Django 5.1.4 on 2024-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('money', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=90)),
                ('U_status', models.CharField(choices=[('Civil', 'Civil'), ('Warrior', 'Warrior'), ('Archery', 'Archery'), ('Wizard', 'Wizard')], max_length=60)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
