# Generated by Django 5.1.4 on 2024-12-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='U_status',
            new_name='u_status',
        ),
    ]
