# Generated by Django 5.1.4 on 2024-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_u_status_user_u_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_status',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Warrior', 'Warrior'), ('Archery', 'Archery'), ('Wizard', 'Wizard')], default='Warrior', max_length=60),
        ),
    ]
