# Generated by Django 5.1.4 on 2024-12-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Guns', 'Guns'), ('Tools', 'Tools'), ('Armor', 'Armor'), ('Transport', 'Transport')], max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('protectionForMagic', models.BooleanField(default=False)),
                ('protectionForCourts', models.BooleanField(default=False)),
                ('protectionForHits', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('author', models.CharField(max_length=100)),
                ('recommendedFor', models.CharField(choices=[('Wizard', 'Wizard'), ('Warrior', 'Warrior'), ('Archer', 'Archer')], max_length=50)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('agricultural', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('maxSpeed', models.IntegerField()),
                ('chargeLevel', models.CharField(choices=[('Light', 'Light'), ('Heavy', 'Heavy'), ('VeryHeavy', 'Very Heavy')], max_length=30)),
            ],
            bases=('products.product',),
        ),
    ]
