# Generated by Django 6.0.6 on 2026-06-05 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, choices=[('Guns', 'Guns'), ('Tools', 'Tools'), ('Armor', 'Armor'), ('Transport', 'Transport')], default='NULL', max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('used', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('recommended_For', models.CharField(choices=[('Civil', 'Civil'), ('Wizard', 'Wizard'), ('Warrior', 'Warrior'), ('Archer', 'Archer')], default='Civil', max_length=50)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('protection_For_Magic', models.BooleanField(default=False)),
                ('protection_For_Courts', models.BooleanField(default=False)),
                ('protection_For_Hits', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('craftedBy', models.CharField(blank=True, default='NULL', max_length=100, null=True)),
                ('type', models.CharField(choices=[('Sword', 'Sword'), ('Polearm', 'Polearm'), ('Archer', 'Archer'), ('Magical', 'Magical')], max_length=50)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('agricultural', models.BooleanField(default=False)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('charge_Level', models.CharField(choices=[('Light', 'Light'), ('Heavy', 'Heavy'), ('VeryHeavy', 'Very Heavy')], max_length=30)),
            ],
            bases=('products.product',),
        ),
    ]
