# Generated by Django 5.1.4 on 2024-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gun',
            name='recommendedFor',
        ),
        migrations.AddField(
            model_name='gun',
            name='type',
            field=models.CharField(choices=[('Sword', 'Sword'), ('Polearm', 'Polearm'), ('Archer', 'Archer'), ('Magical', 'Magical')], default='Sword', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='recommendedFor',
            field=models.CharField(choices=[('Wizard', 'Wizard'), ('Warrior', 'Warrior'), ('Archer', 'Archer')], default=None, max_length=50),
        ),
    ]
