# Generated by Django 5.1.4 on 2024-12-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_gun_recommendedfor_gun_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
