# Generated by Django 4.2.30 on 2026-09-25 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='protection_For_Courts',
            new_name='protection_for_courts',
        ),
        migrations.RenameField(
            model_name='armor',
            old_name='protection_For_Hits',
            new_name='protection_for_hits',
        ),
        migrations.RenameField(
            model_name='armor',
            old_name='protection_For_Magic',
            new_name='protection_for_magic',
        ),
        migrations.RenameField(
            model_name='gun',
            old_name='craftedBy',
            new_name='crafted_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='recommended_For',
            new_name='recommended_for',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='charge_Level',
            new_name='charge_level',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Guns', 'Guns'), ('Tools', 'Tools'), ('Armor', 'Armor'), ('Transport', 'Transport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
