# Generated by Django 5.1.4 on 2024-12-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recommendedFor',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Wizard', 'Wizard'), ('Warrior', 'Warrior'), ('Archer', 'Archer')], default='Civil', max_length=50),
        ),
    ]
